sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script:
  - cmake --version
  - mkdir build_debug
  - mkdir build_release
  - cd build_debug
  - cmake -DCMAKE_BUILD_TYPE=Debug -G"Unix Makefiles" .. && make && ./test-sstl && ./test-sstl-noexceptions
  - cd ../build_release
  - cmake -DCMAKE_BUILD_TYPE=Release -G"Unix Makefiles" .. && make && ./test-sstl && ./test-sstl-noexceptions

